logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123456
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        multiplier: 2
    publisher-confirm-type: correlated
    publisher-returns: true
